apiVersion: v1
kind: Service
metadata:
  name: exto-api-platformdev
  namespace: platformdev
  labels:
    app.exto/component: exto-api
    app.kubernetes.io/instance: platformdev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: exto
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.exto/component: exto-api
    app.kubernetes.io/instance: platformdev
    app.kubernetes.io/name: exto
---

